name: NET

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    release:
      types: [published]

jobs:
  build:
    uses: mycsharp/github-actions/.github/workflows/dotnet-nuget-build-multi-sdk.yml@main
    with:
      configuration: Release
      dotnet-sdks: |
        8.x
        9.x
        10.x

    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
